E-commerceApp/Areas/Admin/Controllers/ProductController.cs
using E_commerceApp.Data;
using E_commerceApp.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace E_commerceApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        private IWebHostEnvironment _host;

        public ProductController(ApplicationDbContext db, IWebHostEnvironment host)
        {
            _db = db;
            _host = host;
        }
        public IActionResult Index()
        {
            return View(_db.Products.Include(a=>a.ProductTypes).Include(a=>a.ProductTags).ToList());
        }

        //post
        [HttpPost]
        public  IActionResult Index(decimal? lowAmount, decimal? largeAmount)
        {
            var products = _db.Products.Include(c => c.ProductTypes).Include(c => c.ProductTags)
                .Where(c => c.Price >= lowAmount && c.Price <= largeAmount).ToList();
            if(lowAmount==null || largeAmount == null)
            {
                products = _db.Products.Include(c => c.ProductTypes).Include(c => c.ProductTags).ToList();
            }

            return View(products);
        }

        //get
        public IActionResult Create()
        {
            ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.ProductTags.ToList(), "Id", "ProductTag");
            return View();
        }

        //post 
        [HttpPost]
        
        public async Task<IActionResult> Create(Products product, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var searchProduct = _db.Products.FirstOrDefault(c=>c.Name == product.Name);
                if (searchProduct!= null)
                {

                    ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
                    ViewData["TagId"] = new SelectList(_db.ProductTags.ToList(), "Id", "ProductTag");
                    return View(product);
                }
                if(image!= null)
                {
                    var name = Path.Combine(_host.WebRootPath + "/images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    product.Image = "images/" + image.FileName;
                }
                if (image == null)
                {
                    product.Image = "images/noimage.PNG";
                }
                _db.Products.Add(product);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
             return View(product);
        }

        //get
        public IActionResult Edit(int? id)
        {
            ViewData["ProductTypeId"] = new SelectList(_db.ProductTypes.ToList(), "Id", "ProductType");
            ViewData["TagId"] = new SelectList(_db.ProductTags.ToList(), "Id", "ProductTag");
            

            if (id == null)
            {
                return NotFound();
            }

            var product = _db.Products
                .Include(b => b.ProductTypes)
                .Include(b => b.ProductTags)
                .FirstOrDefault(b => b.ID == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //post
        [HttpPost]
        public async Task<IActionResult> Edit(Products products, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    var name = Path.Combine(_host.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }

                if (image == null)
                {
                    products.Image = "Images/noimage.PNG";
                }
                _db.Products.Update(products);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(products);
        }

        //get
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products
                .Include(b => b.ProductTypes)
                .Include(b=>b.ProductTags)
                .FirstOrDefault(b=>b.ID==id);
            if(product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //get 
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.Products
                .Include(b=>b.ProductTypes)
                .Include(b=>b.ProductTags)
                .Where(b=>b.ID==id)
                .FirstOrDefault();
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //post action method 
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = _db.Products.FirstOrDefault(c => c.ID == id);
            if(product == null)
            {
                return NotFound();
            }
            _db.Products.Remove(product);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

E-commerceApp/Areas/Admin/Controllers/ProductTagsController.cs
using Microsoft.AspNetCore.Mvc;
using E_commerceApp.Data;
using System.Linq;
using System.Threading.Tasks;
using E_commerceApp.Models;

namespace E_commerceApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTagsController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ProductTagsController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //var data = _db.productTags.ToList();
            return View(_db.ProductTags.ToList());
        }

        //get action method

        public ActionResult Create()
        {
            return View();
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTags productTags)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTags.Add(productTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTags);
        }

        //get action method

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productTag = _db.ProductTags.FirstOrDefault(x => x.Id == id);
            if (productTag == null)
            {
                return NotFound();
            }
            return View(productTag);
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTags productTags)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTags);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTags);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productTag = _db.ProductTags.FirstOrDefault(x => x.Id == id);
            if (productTag == null)
            {
                return NotFound();
            }
            return View(productTag);
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductTags productTags)
        {

            return RedirectToAction(nameof(Index));


        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productTag = _db.ProductTags.Find(id);
            if (productTag == null)
            {
                return NotFound();
            }
            return View(productTag);
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, ProductTags productTags)
        {
            var productTag = _db.ProductTags.Find(id);
            if (id == null || id != productTags.Id || productTag == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _db.Remove(productTag);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTags);
        }
    }
}

E-commerceApp/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Mvc;
using E_commerceApp.Data;
using System.Linq;
using System.Threading.Tasks;
using E_commerceApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace E_commerceApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Super User")]
    public class ProductTypesController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ProductTypesController(ApplicationDbContext db)
        {
            _db=db;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            //var data = _db.productTypes.ToList();
            return View(_db.ProductTypes.ToList()) ;
        }

        //get action method

        public ActionResult Create()
        {
            return View();
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.ProductTypes.Add(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }

        //get action method

        public ActionResult Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.FirstOrDefault(x => x.Id == id);
            if(productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                _db.Update(productTypes);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.FirstOrDefault(x => x.Id == id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Details(ProductTypes productTypes)
        {
            
                return RedirectToAction(nameof(Index));
           
            
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var productType = _db.ProductTypes.Find(id);
            if (productType == null)
            {
                return NotFound();
            }
            return View(productType);
        }

        //post action method 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete( int? id , ProductTypes productTypes)
        {
            var productType = _db.ProductTypes.Find(id);
            if(id == null || id != productTypes.Id || productType == null )
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(productTypes);
        }
    }
}

E-commerceApp/Views/Shared/_ButtonPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int 
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit"  class="btn btn-primary" asp-route-id="@Model">Edit</a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model">Details</a>
        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@Model">Delete</a>
    </div>
</td>
@{
}

E-commerceApp/Views/Shared/_ButtonTagPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int 
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="ProductTags" class="btn btn-primary" asp-route-id="@Model">Edit</a>
        <a asp-action="Details" asp-controller="ProductTags" class="btn btn-success" asp-route-id="@Model">Details</a>
        <a asp-action="Delete" asp-controller="ProductTags" class="btn btn-danger" asp-route-id="@Model">Delete</a>
    </div>
</td>

E-commerceApp/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using E_commerceApp.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString("roleName");
    int count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products==null)
    {
        products=new List<Products>();
    }
    count = products.Count();
   
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_commerceApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_commerceApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductTags" asp-action="Index">Product Tags</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">Shopping Cart @(count)</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - E_commerceApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

E-commerceApp/Views/Shared/_PartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <div class="btn-group">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">
            Edit
        </a>
        <a asp-action="Details" class="btn btn-success" asp-route-id="@Model">Details</a>
        <a asp-action="Lockout" class="btn btn-danger" asp-route-id="@Model">
            Delete
        </a>
    </div>